import { Theme, ThemeId } from '@/types';

export const themes: Record<ThemeId, Theme> = {
  'minimal-light': {
    id: 'minimal-light',
    name: 'Minimal Light',
    isPro: false,
    background: 'bg-gray-50',
    cardBg: 'bg-white',
    textColor: 'text-gray-900',
    buttonBg: 'bg-gray-900',
    buttonText: 'text-white',
    buttonHover: 'hover:bg-gray-700',
    accentColor: 'text-gray-600',
  },
  'minimal-dark': {
    id: 'minimal-dark',
    name: 'Minimal Dark',
    isPro: false,
    background: 'bg-gray-900',
    cardBg: 'bg-gray-800',
    textColor: 'text-white',
    buttonBg: 'bg-white',
    buttonText: 'text-gray-900',
    buttonHover: 'hover:bg-gray-200',
    accentColor: 'text-gray-400',
  },
  'gradient-sunset': {
    id: 'gradient-sunset',
    name: 'Sunset Gradient',
    isPro: false,
    background: 'bg-gradient-to-br from-orange-400 via-pink-500 to-purple-600',
    cardBg: 'bg-white/10 backdrop-blur-lg',
    textColor: 'text-white',
    buttonBg: 'bg-white/20 backdrop-blur',
    buttonText: 'text-white',
    buttonHover: 'hover:bg-white/30',
    accentColor: 'text-white/80',
  },
  'gradient-ocean': {
    id: 'gradient-ocean',
    name: 'Ocean Gradient',
    isPro: true,
    background: 'bg-gradient-to-br from-cyan-400 via-blue-500 to-indigo-600',
    cardBg: 'bg-white/10 backdrop-blur-lg',
    textColor: 'text-white',
    buttonBg: 'bg-white/20 backdrop-blur',
    buttonText: 'text-white',
    buttonHover: 'hover:bg-white/30',
    accentColor: 'text-white/80',
  },
  'gradient-forest': {
    id: 'gradient-forest',
    name: 'Forest Gradient',
    isPro: true,
    background: 'bg-gradient-to-br from-green-400 via-emerald-500 to-teal-600',
    cardBg: 'bg-white/10 backdrop-blur-lg',
    textColor: 'text-white',
    buttonBg: 'bg-white/20 backdrop-blur',
    buttonText: 'text-white',
    buttonHover: 'hover:bg-white/30',
    accentColor: 'text-white/80',
  },
  'neon-pink': {
    id: 'neon-pink',
    name: 'Neon Pink',
    isPro: true,
    background: 'bg-black',
    cardBg: 'bg-gray-900 border border-pink-500/50',
    textColor: 'text-pink-400',
    buttonBg: 'bg-pink-500/20 border border-pink-500',
    buttonText: 'text-pink-400',
    buttonHover: 'hover:bg-pink-500/40',
    accentColor: 'text-pink-300',
  },
  'neon-blue': {
    id: 'neon-blue',
    name: 'Neon Blue',
    isPro: true,
    background: 'bg-black',
    cardBg: 'bg-gray-900 border border-cyan-500/50',
    textColor: 'text-cyan-400',
    buttonBg: 'bg-cyan-500/20 border border-cyan-500',
    buttonText: 'text-cyan-400',
    buttonHover: 'hover:bg-cyan-500/40',
    accentColor: 'text-cyan-300',
  },
  'neon-green': {
    id: 'neon-green',
    name: 'Neon Green',
    isPro: true,
    background: 'bg-black',
    cardBg: 'bg-gray-900 border border-green-500/50',
    textColor: 'text-green-400',
    buttonBg: 'bg-green-500/20 border border-green-500',
    buttonText: 'text-green-400',
    buttonHover: 'hover:bg-green-500/40',
    accentColor: 'text-green-300',
  },
  'glassmorphism': {
    id: 'glassmorphism',
    name: 'Glassmorphism',
    isPro: true,
    background: 'bg-gradient-to-br from-violet-500 via-purple-500 to-fuchsia-500',
    cardBg: 'bg-white/20 backdrop-blur-xl border border-white/30',
    textColor: 'text-white',
    buttonBg: 'bg-white/30 backdrop-blur border border-white/40',
    buttonText: 'text-white',
    buttonHover: 'hover:bg-white/40',
    accentColor: 'text-white/90',
  },
  'brutalist': {
    id: 'brutalist',
    name: 'Brutalist',
    isPro: true,
    background: 'bg-yellow-300',
    cardBg: 'bg-white border-4 border-black',
    textColor: 'text-black',
    buttonBg: 'bg-black',
    buttonText: 'text-yellow-300',
    buttonHover: 'hover:bg-gray-800',
    accentColor: 'text-black',
  },
  'retro-wave': {
    id: 'retro-wave',
    name: 'Retro Wave',
    isPro: true,
    background: 'bg-gradient-to-b from-purple-900 via-pink-900 to-orange-900',
    cardBg: 'bg-black/40 backdrop-blur',
    textColor: 'text-pink-300',
    buttonBg: 'bg-gradient-to-r from-pink-500 to-orange-500',
    buttonText: 'text-white',
    buttonHover: 'hover:from-pink-600 hover:to-orange-600',
    accentColor: 'text-cyan-400',
  },
  'pastel-dream': {
    id: 'pastel-dream',
    name: 'Pastel Dream',
    isPro: true,
    background: 'bg-gradient-to-br from-pink-200 via-purple-200 to-blue-200',
    cardBg: 'bg-white/60 backdrop-blur',
    textColor: 'text-gray-700',
    buttonBg: 'bg-white/80',
    buttonText: 'text-purple-600',
    buttonHover: 'hover:bg-white',
    accentColor: 'text-purple-500',
  },
  'dark-elegant': {
    id: 'dark-elegant',
    name: 'Dark Elegant',
    isPro: true,
    background: 'bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900',
    cardBg: 'bg-gray-800/50 backdrop-blur border border-gray-700',
    textColor: 'text-gray-100',
    buttonBg: 'bg-gradient-to-r from-amber-500 to-orange-500',
    buttonText: 'text-white',
    buttonHover: 'hover:from-amber-600 hover:to-orange-600',
    accentColor: 'text-amber-400',
  },
  'nature-earth': {
    id: 'nature-earth',
    name: 'Nature Earth',
    isPro: true,
    background: 'bg-gradient-to-br from-amber-100 via-lime-100 to-emerald-100',
    cardBg: 'bg-white/70 backdrop-blur',
    textColor: 'text-emerald-900',
    buttonBg: 'bg-emerald-600',
    buttonText: 'text-white',
    buttonHover: 'hover:bg-emerald-700',
    accentColor: 'text-emerald-600',
  },
  'cyberpunk': {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    isPro: true,
    background: 'bg-gradient-to-br from-gray-900 via-purple-900 to-gray-900',
    cardBg: 'bg-black/60 backdrop-blur border border-yellow-500/30',
    textColor: 'text-yellow-400',
    buttonBg: 'bg-yellow-500',
    buttonText: 'text-black',
    buttonHover: 'hover:bg-yellow-400',
    accentColor: 'text-cyan-400',
  },
  'minimalist-mono': {
    id: 'minimalist-mono',
    name: 'Minimalist Mono',
    isPro: true,
    background: 'bg-white',
    cardBg: 'bg-gray-50 border border-gray-200',
    textColor: 'text-gray-900',
    buttonBg: 'bg-gray-100 border border-gray-300',
    buttonText: 'text-gray-700',
    buttonHover: 'hover:bg-gray-200',
    accentColor: 'text-gray-500',
  },
  'warm-autumn': {
    id: 'warm-autumn',
    name: 'Warm Autumn',
    isPro: true,
    background: 'bg-gradient-to-br from-orange-200 via-red-200 to-amber-200',
    cardBg: 'bg-white/70 backdrop-blur',
    textColor: 'text-orange-900',
    buttonBg: 'bg-orange-600',
    buttonText: 'text-white',
    buttonHover: 'hover:bg-orange-700',
    accentColor: 'text-orange-600',
  },
  'cool-winter': {
    id: 'cool-winter',
    name: 'Cool Winter',
    isPro: true,
    background: 'bg-gradient-to-br from-slate-200 via-blue-200 to-cyan-200',
    cardBg: 'bg-white/70 backdrop-blur',
    textColor: 'text-slate-800',
    buttonBg: 'bg-slate-700',
    buttonText: 'text-white',
    buttonHover: 'hover:bg-slate-800',
    accentColor: 'text-blue-600',
  },
  'spring-bloom': {
    id: 'spring-bloom',
    name: 'Spring Bloom',
    isPro: true,
    background: 'bg-gradient-to-br from-green-200 via-pink-200 to-yellow-200',
    cardBg: 'bg-white/70 backdrop-blur',
    textColor: 'text-green-900',
    buttonBg: 'bg-pink-500',
    buttonText: 'text-white',
    buttonHover: 'hover:bg-pink-600',
    accentColor: 'text-pink-500',
  },
  'summer-vibes': {
    id: 'summer-vibes',
    name: 'Summer Vibes',
    isPro: true,
    background: 'bg-gradient-to-br from-yellow-300 via-orange-300 to-red-300',
    cardBg: 'bg-white/70 backdrop-blur',
    textColor: 'text-orange-900',
    buttonBg: 'bg-red-500',
    buttonText: 'text-white',
    buttonHover: 'hover:bg-red-600',
    accentColor: 'text-red-500',
  },
};

export const freeThemes: ThemeId[] = ['minimal-light', 'minimal-dark', 'gradient-sunset'];
export const proThemes: ThemeId[] = Object.keys(themes).filter(
  (id) => !freeThemes.includes(id as ThemeId)
) as ThemeId[];

export function getTheme(id: ThemeId): Theme {
  return themes[id] || themes['minimal-light'];
}

export function canUseTheme(themeId: ThemeId, isPro: boolean): boolean {
  if (isPro) return true;
  return freeThemes.includes(themeId);
}
